<option value="19 de Agosto">19 de Agosto</option>
<option value="1st">1st</option>
<option value="2nd">2nd</option>
<option value="3rd">3rd</option>
<option value="Alcantara">Alcantara</option>
<option value="Alex">Alex</option>
<option value="Alfredo">Alfredo</option>
<option value="Algeciras">Algeciras</option>
<option value="Algueria">Algueria</option>
<option value="Altura">Altura</option>
<option value="Altura Extension">Altura Extension</option>
<option value="Amelia">Amelia</option>
<option value="Antipolo">Antipolo</option>
<option value="Antonio">Antonio</option>
<option value="Arevalo Street">Arevalo Street</option>
<option value="Arsenio H. Lacson Avenue">Arsenio H. Lacson Avenue</option>
<option value="B. Tuazon">B. Tuazon</option>
<option value="Bagong Buhay Street">Bagong Buhay Street</option>
<option value="Basilio">Basilio</option>
<option value="Batanes">Batanes</option>
<option value="Bayani">Bayani</option>
<option value="Benny">Benny</option>
<option value="Blumentritt">Blumentritt</option>
<option value="Blumentritt Road">Blumentritt Road</option>
<option value="Bohol">Bohol</option>
<option value="Buenos Aires">Buenos Aires</option>
<option value="Calabash Road">Calabash Road</option>
<option value="Calabash-A">Calabash-A</option>
<option value="Calabash-B">Calabash-B</option>
<option value="Callejon Felipa">Callejon Felipa</option>
<option value="Carola">Carola</option>
<option value="Castanos">Castanos</option>
<option value="Centro">Centro</option>
<option value="Craig">Craig</option>
<option value="D Santiago">D Santiago</option>
<option value="Dapitan">Dapitan</option>
<option value="De los Reyes">De los Reyes</option>
<option value="Dimasalang">Dimasalang</option>
<option value="Dimasalang Street">Dimasalang Street</option>
<option value="Domingo Santiago">Domingo Santiago</option>
<option value="Don Benito Legarda">Don Benito Legarda</option>
<option value="Don Quijote">Don Quijote</option>
<option value="Dos Castillas">Dos Castillas</option>
<option value="E. Rodriguez Sr. Avenue">E. Rodriguez Sr. Avenue</option>
<option value="Extremadura">Extremadura</option>
<option value="F. Jhocson">F. Jhocson</option>
<option value="Fajardo Ext">Fajardo Ext</option>
<option value="Felina">Felina</option>
<option value="Ferdinand Blumentritt">Ferdinand Blumentritt</option>
<option value="Firmeza">Firmeza</option>
<option value="Florentino Cayco Street">Florentino Cayco Street</option>
<option value="FootbridgefootwayG. Sanciangco">FootbridgefootwayG. Sanciangco</option>
<option value="G. Tuazon">G. Tuazon</option>
<option value="G. Tuazon Interior">G. Tuazon Interior</option>
<option value="Galicia">Galicia</option>
<option value="Gelinos">Gelinos</option>
<option value="Gen. E. Quintos">Gen. E. Quintos</option>
<option value="Gen. Geronimo">Gen. Geronimo</option>
<option value="General Concepcion">General Concepcion</option>
<option value="General Geronimo">General Geronimo</option>
<option value="Gerardo">Gerardo</option>
<option value="Halcon">Halcon</option>
<option value="Hipodromo">Hipodromo</option>
<option value="Honoradez">Honoradez</option>
<option value="Honoradez Ext">Honoradez Ext</option>
<option value="Honorio Ventura">Honorio Ventura</option>
<option value="Honradez">Honradez</option>
<option value="Ibarra">Ibarra</option>
<option value="Ibarra Street">Ibarra Street</option>
<option value="Ilaw ng Nayon">Ilaw ng Nayon</option>
<option value="Instruccion">Instruccion</option>
<option value="Jacobo Fajardo">Jacobo Fajardo</option>
<option value="Jacobo Fajardo Street">Jacobo Fajardo Street</option>
<option value="Jaime">Jaime</option>
<option value="Jhocson">Jhocson</option>
<option value="Josefina">Josefina</option>
<option value="Josefina III">Josefina III</option>
<option value="Kasama">Kasama</option>
<option value="Kundiman">Kundiman</option>
<option value="L. Ma. Guerrero Drive">L. Ma. Guerrero Drive</option>
<option value="L. Roces">L. Roces</option>
<option value="Laon Laan Road">Laon Laan Road</option>
<option value="Laon Laan Street">Laon Laan Street</option>
<option value="Lardizabal">Lardizabal</option>
<option value="Legarda">Legarda</option>
<option value="Legarda Flyover">Legarda Flyover</option>
<option value="Leo">Leo</option>
<option value="Leyte">Leyte</option>
<option value="Leyte Del Sur">Leyte Del Sur</option>
<option value="Ligaya">Ligaya</option>
<option value="Loreto">Loreto</option>
<option value="Luzon Avenue">Luzon Avenue</option>
<option value="Luzon Avenue Extension">Luzon Avenue Extension</option>
<option value="M Dela Fuente">M Dela Fuente</option>
<option value="M Dela Fuente Street"></option>
<option value="M Santiago">M Santiago</option>
<option value="M T Halili">M T Halili</option>
<option value="M. Arenas">M. Arenas</option>
<option value="M. Dela Fuente Street">M. Dela Fuente Street</option>
<option value="M. Earnshaw Street">M. Earnshaw Street</option>
<option value="M. F. Jhocson">M. F. Jhocson</option>
<option value="M.F. Jocson">M.F. Jocson</option>
<option value="Mabini StreetpedestrianMaceda">Mabini StreetpedestrianMaceda</option>
<option value="Maceda Street">Maceda Street</option>
<option value="Maganda">Maganda</option>
<option value="Malamig">Malamig</option>
<option value="Mangga Avenue">Mangga Avenue</option>
<option value="Mansanas">Mansanas</option>
<option value="Maria Clara Street">Maria Clara Street</option>
<option value="Maria Cristina">Maria Cristina</option>
<option value="Maria Luisa">Maria Luisa</option>
<option value="Marquitos">Marquitos</option>
<option value="Marquitos Street">Marquitos Street</option>
<option value="Marzan">Marzan</option>
<option value="Masbate">Masbate</option>
<option value="Matimyas">Matimyas</option>
<option value="Matimyas Road">Matimyas Road</option>
<option value="Mayon">Mayon</option>
<option value="Mercedes">Mercedes</option>
<option value="Mercedez Street">Mercedez Street</option>
<option value="Metrica">Metrica</option>
<option value="Micsino Drive">Micsino Drive</option>
<option value="Miguel">Miguel</option>
<option value="Miguelin">Miguelin</option>
<option value="Mindanao Avenue">Mindanao Avenue</option>
<option value="Mindanao Avenue Extension">Mindanao Avenue Extension</option>
<option value="Mindoro">Mindoro</option>
<option value="Mithi">Mithi</option>
<option value="Montana">Montana</option>
<option value="Moret">Moret</option>
<option value="Negros">Negros</option>
<option value="Nicanor Ramirez">Nicanor Ramirez</option>
<option value="Norma">Norma</option>
<option value="Old Santa Mesa">Old Santa Mesa</option>
<option value="Osmeña Drive">Osmeña Drive</option>
<option value="P Pelaez">P Pelaez</option>
<option value="P. Florentino Street">P. Florentino Street</option>
<option value="P. Guevarra">P. Guevarra</option>
<option value="P. Noval Street">P. Noval Street</option>
<option value="Palanza">Palanza</option>
<option value="Palawan">Palawan</option>
<option value="Paltok">Paltok</option>
<option value="Panay">Panay</option>
<option value="Paraiso">Paraiso</option>
<option value="Piña Avenue">Piña Avenue</option>
<option value="Piy Margal Street">Piy Margal Street</option>
<option value="Plaza Noli">Plaza Noli</option>
<option value="Prudencio">Prudencio</option>
<option value="Pureza">Pureza</option>
<option value="Quezon Drive">Quezon Drive</option>
<option value="Quintos">Quintos</option>
<option value="Ramon Magsaysay">Ramon Magsaysay</option>
<option value="Ramon Magsaysay Service Road">Ramon Magsaysay Service Road</option>
<option value="Ramon Magsaysay Service Road U-Turn Slot">Ramon Magsaysay Service Road U-Turn Slot</option>
<option value="Remedios">Remedios</option>
<option value="Road 10">Road 10</option>
<option value="Romblon">Romblon</option>
<option value="Roxas">Roxas</option>
<option value="Ruaño Drive">Ruaño Drive</option>
<option value="Ruperto Cristobal">Ruperto Cristobal</option>
<option value="Samar">Samar</option>
<option value="San Agustin">San Agustin</option>
<option value="San Antonio">San Antonio</option>
<option value="San Diego">San Diego</option>
<option value="San Jose">San Jose</option>
<option value="Sancho Panza">Sancho Panza</option>
<option value="Santa Teresita">Santa Teresita</option>
<option value="Santissima Trinidad">Santissima Trinidad</option>
<option value="Santo Tomas">Santo Tomas</option>
<option value="Santo Tomas Road">Santo Tomas Road</option>
<option value="Santol">Santol</option>
<option value="Sergio H. Loyola">Sergio H. Loyola</option>
<option value="Service road">Service road</option>
<option value="Silencio">Silencio</option>
<option value="Sinigian Drive">Sinigian Drive</option>
<option value="Sisa">Sisa</option>
<option value="Sobriedad">Sobriedad</option>
<option value="Sobriedad Ext">Sobriedad Ext</option>
<option value="Sta Clara">Sta Clara</option>
<option value="Sta Cruz">Sta Cruz</option>
<option value="Sto Tomas Road">Sto Tomas Road</option>
<option value="Sulucan">Sulucan</option>
<option value="Susan">Susan</option>
<option value="Susan Street">Susan Street</option>
<option value="T Alfonso">T Alfonso</option>
<option value="T Anzures">T Anzures</option>
<option value="T. Pinpin">T. Pinpin</option>
<option value="Tacio">Tacio</option>
<option value="Tamayo Drive">Tamayo Drive</option>
<option value="V Alindada">V Alindada</option>
<option value="Valdez">Valdez</option>
<option value="Valencia">Valencia</option>
<option value="Valencia Street">Valencia Street</option>
<option value="Verdad">Verdad</option>
<option value="Vicente Cruz">Vicente Cruz</option>
<option value="Vicente Cruz Street">Vicente Cruz Street</option>
<option value="Vigan">Vigan</option>
<option value="Villamor Drive">Villamor Drive</option>
<option value="Visayan Avenue">Visayan Avenue</option>
<option value="West Vigan">West Vigan</option>